# Generated by Django 5.1.4 on 2026-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('token_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='revoked_expires_idx')],
            },
        ),
    ]
