"""empty message

Revision ID: 51056705afef
Revises: 3941a2daebba
Create Date: 2022-02-05 01:08:14.504942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51056705afef'
down_revision = '3941a2daebba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('add_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'add_date')
    # ### end Alembic commands ###
