"""post and processed_events

Revision ID: 3eeb74668e09
Revises: 
Create Date: 2026-07-21 21:47:07.807231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3eeb74668e09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('body', sa.String(length=1500), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('related', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))

    op.drop_table('post')
    # ### end Alembic commands ###
